## Creating multiple nodes using Vagrant

$scriptansible = <<-SCRIPT
echo Installing Updates & Ansible
yum install epel-release -y && yum install ansible -y
SCRIPT



Vagrant.configure("2") do |config|
  config.vm.define "mnode" do |mnode|
    mnode.vm.box = "bento/centos-7.3"
    mnode.vm.network "public_network", ip: "192.168.87.250"
    mnode.ssh.username = "vagrant"
    mnode.ssh.password = "vegrant"
    mnode.ssh.insert_key = true
    mnode.ssh.pty = false
    mnode.vm.provider "virtualbox" do |vm|
      vm.gui = true
      vm.customize ["modifyvm", :id, "--memory", 1024]
      vm.customize ["modifyvm", :id, "--cpus", 1]
      vm.customize ["modifyvm", :id, "--vram", "256"]
    end
    mnode.vm.provision "shell", inline: $scriptansible
  end
end